<a href="https://colab.research.google.com/github/JairGF05/funciones_principales_numpy/blob/main/funciones_principales_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **Definición de números aleatorios**

In [2]:
#Un solo número entero aleatorio entre 1y 20
np.random.randint(1,20)

2

In [3]:
#Arreglo con 10 números aleatorios entre 1 y 20
arr = np.random.randint(1,20,10)
arr

array([12,  8, 10, 15, 16,  4,  5, 15, 15, 16])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[12,  8, 10, 15, 16],
       [ 4,  5, 15, 15, 16]])

# **Obtener el valor Mayor del array**

In [5]:
#array
max = arr.max()
max


16

In [6]:
#matriz
max_mat = matriz.max()
max_mat

16

In [7]:
#Puedo obtener el maximo por fila de la matriz, especificando por que eje , en este caso por filas
matriz


array([[12,  8, 10, 15, 16],
       [ 4,  5, 15, 15, 16]])

In [8]:
#En este caso el número mayor de la primer fila es 19 y de la segunda fila es 10
matriz.max(1) #el eje 1 son filas

array([16, 16])

In [9]:
#obteniendo el mayor por columnas , es decir, el eje 0
matriz.max(0)

array([12,  8, 15, 15, 16])

**argmax:**  nos dice en que indice se encuentra el valor más grande de nuestro array

In [10]:
#ejemplos
#En nuestro array elvalor más grande se encuentra en el indice 3
arr.argmax()

4

In [11]:
#En caso de que haya dos valores repetidos, argmax siempre muestra el de menor indice
matriz.argmax()

4

# **Obtener el valor menor de un array**

**min:** nos devuelve el valor más pequeño del array o matriz 

In [12]:
arr.min()

4

In [13]:
matriz.min()

4

In [14]:
matriz

array([[12,  8, 10, 15, 16],
       [ 4,  5, 15, 15, 16]])

In [15]:
#minimo por filas y columnas con 0 y 1, este como argmax nos muestra los indices
matriz.argmin(0)

array([1, 1, 0, 0, 0])

In [16]:
matriz.argmin(1)

array([1, 0])

# **Pick to Pick ptp**
Nos indica la diferencia que hay entre el valor más grande y el valor más pequeño.

In [17]:
arr

array([12,  8, 10, 15, 16,  4,  5, 15, 15, 16])

In [18]:
#En este caso el valor menor es 2 y el maximo es 18, por lo que la diferencia entre ambos es de 16
arr.ptp()

12

In [19]:
matriz

array([[12,  8, 10, 15, 16],
       [ 4,  5, 15, 15, 16]])

In [20]:
matriz.ptp()

12

In [21]:
#En una matriz se puede seleccionar el eje
#En este caso por columnas
matriz.ptp(0)

array([8, 3, 5, 0, 0])

In [22]:
#Por filas
matriz.ptp(1)

array([ 8, 12])

# **Percentile**
Me va a especificar directamente el percentil que stoy trabajando.
El percentil es una medida de posición usada en estadística que indica, una vez ordenados los datos de menor a mayor, el valor de la variable por debajo del cual se encuentra un porcentaje dado de observaciones en un grupo.
 For example, if you are at the 80th percentile for height in a group of people, that means 80% of people in that group are shorter than you.

In [23]:
arr

array([12,  8, 10, 15, 16,  4,  5, 15, 15, 16])

In [24]:
np.percentile(arr, 50)

13.5

In [25]:
#Percentil 0 es el número más bajo
np.percentile(arr, 0)

4.0

In [26]:
#Percentil 100 es el número más alto
np.percentile(arr, 100)

16.0

**sort:** permite ordenar un arreglo

In [27]:
#Por eeso el percentil 50 es 8 , suma 9 + 7 y  lo divide entre 2 , pero los valores deben estar ordenados
arr.sort()
arr

array([ 4,  5,  8, 10, 12, 15, 15, 15, 16, 16])

# **Obtener la mediana**
La mediana es un valor que divide un conjunto de datos en dos partes iguales. Es una medida de tendencia central que se utiliza para representar el valor “típico” de un conjunto de datos. Para calcular la mediana, primero se ordenan los datos de menor a mayor y luego se selecciona el valor del medio. Si el número de datos es par, la mediana es el promedio de los dos valores centrales.

Para calcular la mediana de un conjunto de datos, primero debes ordenar los datos de menor a mayor. Si el número de datos es impar, la mediana es el valor que está justo en el medio. Por ejemplo, si tienes 5 datos: 1, 3, 4, 6 y 8, la mediana sería 4.

Si el número de datos es par, la mediana es el promedio de los dos valores centrales. Por ejemplo, si tienes 6 datos: 1, 3, 4, 6, 8 y 9, los dos valores centrales son 4 y 6. La mediana sería (4 + 6) / 2 = 5.

In [28]:
arr

array([ 4,  5,  8, 10, 12, 15, 15, 15, 16, 16])

In [29]:
#La emdiana y el percentil 50 son exactamente lo mismo
np.median(arr)

13.5

In [30]:
#En la matriz se puede obtener la mediana por los ejes 0 y 1
np.median(matriz,0) #filas

array([ 9.5, 10. , 11.5, 13. , 14. ])

In [31]:
np.median(matriz, 1)#columnas

array([ 8., 15.])

# **Obtener la desviación estandar**
La desviación estándar es un índice numérico de la dispersión de un conjunto de datos (o población). Mientras mayor es la desviación estándar, mayor es la dispersión de la población. La desviación estándar es un promedio de las desviaciones individuales de cada observación con respecto a la media de una distribución.

Para calcular la desviación estándar de una muestra de datos, primero debes hallar la media aritmética de los datos. Luego, debes calcular las desviaciones de cada dato respecto a la media (restar la media a cada dato). Después, debes elevar al cuadrado cada una de estas desviaciones y sumarlas todas. Finalmente, debes dividir el resultado entre el número total de datos y calcular la raíz cuadrada del resultado.

Ejemplo: 
1.   Primero calculamos la media aritmética: (2 + 4 + 6 + 8 + 10) / 5 = 6.
2.   Luego calculamos las desviaciones de cada dato respecto a la media: 2 - 6 = -4, 4 - 6 = -2, 6 - 6 = 0, 8 - 6 = 2 y 10 - 6 = 4.
3.   Después elevamos al cuadrado cada una de estas desviaciones y las sumamos todas: (-4)^2 + (-2)^2 + (0)^2 + (2)^2 + (4)^2 = 40.
4.  
Finalmente dividimos el resultado entre el número total de datos y calculamos la raíz cuadrada del resultado: √(40 / 5) ≈ 2.83.
Por lo tanto, la desviación estándar de esta muestra de datos es aproximadamente 2.83.



In [32]:
arr

array([ 4,  5,  8, 10, 12, 15, 15, 15, 16, 16])

In [33]:
np.std(arr)

4.363484845854286

# **Varianza**
La varianza es una medida de dispersión que representa la variabilidad de una serie de datos respecto a su media.
Supongamos que tenemos un conjunto de datos: 2, 4, 4, 4, 5, 5, 7, 9.

Primero calculamos la media de los datos: (2+4+4+4+5+5+7+9)/8 = 5.

Luego calculamos los residuos al cuadrado: (2-5)² = 9; (4-5)² = 1; (4-5)² = 1; (4-5)² = 1; (5-5)² = 0; (5-5)² = 0; (7-5)² = 4; (9-5)² = 16.

Finalmente sumamos los residuos al cuadrado y dividimos entre el total de observaciones: (9+1+1+1+0+0+4+16)/8 = 4.5.

Entonces la varianza de este conjunto de datos es 4.5.

Nota: La desviación estandar elevada al cuadrado es igual a la varianza

In [34]:
arr

array([ 4,  5,  8, 10, 12, 15, 15, 15, 16, 16])

In [35]:
np.var(arr)

19.040000000000003

# **Obtener e promedio o la media**

In [36]:
arr

array([ 4,  5,  8, 10, 12, 15, 15, 15, 16, 16])

In [37]:
np.mean(arr)

11.6

# **Concatenación**


In [38]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [61]:
b = np.array([5, 6])
b

array([5, 6])

In [62]:
#concatenando arreglos, las dimensiones deben ser iguales
#se puede checar con a.ndim y b.ndim
#en este caso b solo tiene una dimension , por lo que tenemos que expandir su dimension
b = np.expand_dims(b, axis=0)
b

array([[5, 6]])

In [47]:
a.ndim

2

In [63]:
b.ndim

2

In [64]:
#concatenando
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
#Transpuesta de una matriz, si hay una matriz 3x2 la transpuesta seria 2x3
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])